@host = 192.168.0.2:8000


### /acquisition/set-duration
POST http://{{host}}/acquisition/set-duration?duration=500
Content-Type: text/plain

### /acquisition/set-filename
POST http://{{host}}/acquisition/set-filename?filename=test_run.bin
Content-Type: text/plain

### /acquisition/start
GET http://{{host}}/acquisition/start

### /acquisition/stop
POST http://{{host}}/acquisition/stop

### /acquisition/stream
GET http://{{host}}/acquisition/stream

### /acquisition/download
GET http://{{host}}/acquisition/download?filename=test_run.bin

### /acquisition/list-files
GET http://{{host}}/acquisition/list-files

### /acquisition/delete-all
DELETE http://{{host}}/acquisition/delete-all