### Test the /bias/set-bias endpoint
POST http://192.168.0.2:8000/bias/set-bias?value=200

### Test the /bias/get-bias endpoint
GET http://192.168.0.2:8000/bias/get-bias

### Test the /bias/on endpoint
POST http://192.168.0.2:8000/bias/on

### Test the /bias/off endpoint
POST http://192.168.0.2:8000/bias/off

### Test the /bias/status endpoint
GET http://192.168.0.2:8000/bias/status

### Test the /acquisition/start endpoint
GET http://192.168.0.2:8000/acquisition/start

### Test the /acquisition/set-duration endpoint
POST http://192.168.0.2:8000/acquisition/set-duration?duration=50
Content-Type: text/plain

### Test the /acquisition/set-filename endpoint
POST http://192.168.0.2:8000/acquisition/set-filename?filename=test_run.bin
Content-Type: text/plain

### Test the /acquisition/stop endpoint
POST http://192.168.0.2:8000/acquisition/stop
Content-Type: text/plain

### Test the /acquisition/download endpoint
GET http://192.168.0.2:8000/acquisition/download?filename=test_run.bin

### Test the /acquisition/stream endpoint
GET http://192.168.0.2:8000/acquisition/stream?filename=test_run.bin&max_points=100